FROM golang:latest AS builder
COPY get_xui_alpha_zh.sh get_xui.sh
RUN bash get_xui.sh

FROM alpine:latest
LABEL org.opencontainers.image.authors="https://github.com/Chasing66"
COPY --from=builder /go/x-ui/x-ui /usr/local/bin/x-ui

ENV TZ=Asia/Shanghai
RUN apk add --no-cache ca-certificates tzdata

ARG TARGETARCH
COPY --from=teddysun/xray /usr/bin/xray /usr/local/bin/bin/xray-linux-${TARGETARCH}
COPY --from=teddysun/xray /usr/share/xray/ /usr/local/bin/bin/

VOLUME [ "/etc/x-ui" ]
WORKDIR /usr/local/bin
CMD [ "x-ui" ]
