name: builder 11111

on:
  workflow_dispatch:
  
env:
  caddy_v: 2.9.1
  xui_v: 0.3.4.3

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        #with:
          #submodules: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - 
        name: Get qbee version
        id: qbee_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: c0re100/qBittorrent-Enhanced-Edition
      - 
        run: echo "最新版本为 ${{ steps.qbee_version.outputs.release  }}"
