name: builder qbee_image

on:
  workflow_dispatch:
  
#env:
  #caddy_v: 2.9.1
  #xui_v: 0.3.4.3

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        #with:
          #submodules: true
      - 
        name: Checkout qbee
        uses: actions/checkout@v4 
        with:
          repository: dolphin738/qBittorrent-Enhanced-Edition-Docker
          path: QBEE
      #-        
        #name: Set up QEMU
        #uses: docker/setup-qemu-action@v2
      #-
        #name: Set up Docker Buildx
        #uses: docker/setup-buildx-action@v2
      #- 
        #name: Cache Docker layers
        #uses: actions/cache@v3
        #with:
          #path: /tmp/.buildx-cache
          #key: ${{ runner.os }}-buildx-${{ github.sha }}
          #restore-keys: |
           #${{ runner.os }}-buildx-
      - 
        name: Copy files
        env:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: | 
          sudo mkdir -p /etc/DDSRem &&
          cd /home/runner/work/vps/vps/build_image/qbee
          jq ".Dockerhub_Username = \"dolphin738\" | .Dockerhub_Password = \"dckr_pat_xvmfQxYvRUZxlfknbgLfJLovpIU\"" config.json  > 1.json  &&
          mv 1.json  config.json
          sudo cp -rf config.json  /etc/DDSRem/config.json &&
          echo "$(ls /etc/DDSRem/)" &&
          echo "$(jq -r '.Dockerhub_Username' /etc/DDSRem/config.json)"
          echo "$(jq -r '.Dockerhub_Password' /etc/DDSRem/config.json)"
          echo "当前路径: $(pwd)"
      - 
        name: Execute SH
        run:  |
          cd /home/runner/work/vps/vps/QBEE
          echo "当前路径: $(pwd)"  &&
          echo "当前路径: ${HOME}"  &&
          echo "$(ls /etc/DDSRem/)" &&
          echo "$(jq -r '.Dockerhub_Username' /etc/DDSRem/config.json)"
          echo "$(jq -r '.Dockerhub_Password' /etc/DDSRem/config.json)"
          chmod +x ./Build.sh  &&
           ./Build.sh
      #-
        #name: Login to Docker Hub
        #uses: docker/login-action@v2
        #with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}
      #- 
        #name: Lower case dockerhub image name
        #id: dockerhub_image
        #uses: ASzc/change-string-case-action@v5
        #with:
          #string: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PACKAGE_C }}
      #- 
        #name: Get qbee version
        #id: qbee_version
        #uses: pozetroninc/github-action-get-latest-release@master
        #with:
          #repository: c0re100/qBittorrent-Enhanced-Edition
      #- 
        #run: echo "最新版本为 ${{ steps.qbee_version.outputs.release  }}"
      #-
        #name: Build and push with qbee
        #uses: docker/build-push-action@v4
        #with:
          #context: QBEE
          #file: ./QBEE/Dockerfile
          #platforms: linux/amd64
          #push: true
          #tags: |
            #${{ secrets.DOCKERHUB_USERNAME }}/qbittorrentee:${{ steps.qbee_version.outputs.release  }}
            #${{ secrets.DOCKERHUB_USERNAME }}/qbittorrentee
          #cache-from: type=local,src=/tmp/.buildx-cache
          #cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
     # - 
        #name: Move cache
        #run: |
          #rm -rf /tmp/.buildx-cache
         #mv /tmp/.buildx-cache-new /tmp/.buildx-cache

